### 登录功能实现
POST http://127.0.0.1:8000/ecommerce-authority-center/authority/token
Content-Type: application/json
ecommerce-user: eyJhbGciOiJSUzI1NiJ9.eyJlLWNvbW1lcmNlLXVzZXIiOiJ7XCJpZFwiOjEwLFwidXNlcm5hbWVcIjpcImpzZm1cIn0iLCJqdGkiOiJkMDc0Y2JhMS03MDgzLTQwNzUtODAyNi1jYmNmZDNlOTk2NWEiLCJleHAiOjE2NTEyNDgwMDB9.eb0vTubAMXP3AOwtQDOZ9Xah-ia0V1ev3Bn3iH-lB1kWZueEP3yPOV5Fv06uqsHv4SU7Dok10RUK6et2u-dlltS0VIEVNGHK69fBtfhZjROG0x_JPtUm6hQVJFMyClCijXbE5bG33IIGkPy06Oa_UAJE4Mt0lPhoOReTd8rktRweq8beZnTFNd9FeNY-e-nlv65RPQgUHLHpDWihxogXMdi9pJM6n2TEXFCajMrcWxIf_1KCfqVQDTH2576gGSRZjPm01l49YgDZpPC-alI_Mhp33y0R2sS4kKF2-_QxwWtE0PZPuHYKGVDO30RBahA0FEwliwNQCviN_tQTvQgmKQ
{
  "username": "jsfm",
  "password": "25d55ad283aa400af464c76d713c07ad"
}

### 注册功能实现
POST http://127.0.0.1:8000/ecommerce-authority-center/authority/register
Content-Type: application/json

{
  "username": "qwq",
  "password": "25d55ad283aa400af464c76d713c07ad"
}
