### 当前登录用户余额信息
GET http://127.0.0.1:9001/njust/ecommerce-account-service/balance/current-balance
accept: application/json
e-commerce-user: eyJhbGciOiJSUzI1NiJ9.eyJlLWNvbW1lcmNlLXVzZXIiOiJ7XCJpZFwiOjEwLFwidXNlcm5hbWVcIjpcImpzZm1cIn0iLCJqdGkiOiI5MGNjMWVmYy0zNzQ4LTQ5NDUtYTAzYi1lMTllYmUyYzk4MzEiLCJleHAiOjE2NTA5ODg4MDB9.G4NFiu38NF8HKqJ9mo6xgbPZeqk6NGw2MBhxYJvWFRA-59UQQIFMjDXm81VpIv1bCEThiaIoke7z2PczG0wDjUTRta8JYJ6zWD7E5gQ2xJlfs6bHADz0uBgf-eF2qbLTgxEpRsccJcWMndCYOZZGh7O9QZOVLBZeiNF8AVmljnvluCiP-pkl37qgp1klsmsg9E305tDmG0P4b4YNKYSW59vC50iluvuEx7TANPb0dLfDZfZL22GyIgUOJ4Gs56ahcvhjFLUQAhg1LQqCzWmmPVMeR4srdek6aWvoXWaz5OVB8Hk_V5JvHmCVEMdjEmlHSSdfAQRWhgAPlqjbomVaIQ

### 扣减用户余额
PUT http://127.0.0.1:9001/njust/ecommerce-account-service/balance/deduct-balance
Content-Type: application/json
e-commerce-user: eyJhbGciOiJSUzI1NiJ9.eyJlLWNvbW1lcmNlLXVzZXIiOiJ7XCJpZFwiOjEwLFwidXNlcm5hbWVcIjpcImpzZm1cIn0iLCJqdGkiOiI5MGNjMWVmYy0zNzQ4LTQ5NDUtYTAzYi1lMTllYmUyYzk4MzEiLCJleHAiOjE2NTA5ODg4MDB9.G4NFiu38NF8HKqJ9mo6xgbPZeqk6NGw2MBhxYJvWFRA-59UQQIFMjDXm81VpIv1bCEThiaIoke7z2PczG0wDjUTRta8JYJ6zWD7E5gQ2xJlfs6bHADz0uBgf-eF2qbLTgxEpRsccJcWMndCYOZZGh7O9QZOVLBZeiNF8AVmljnvluCiP-pkl37qgp1klsmsg9E305tDmG0P4b4YNKYSW59vC50iluvuEx7TANPb0dLfDZfZL22GyIgUOJ4Gs56ahcvhjFLUQAhg1LQqCzWmmPVMeR4srdek6aWvoXWaz5OVB8Hk_V5JvHmCVEMdjEmlHSSdfAQRWhgAPlqjbomVaIQ

{
  "userID": 10,
  "balance": 200
}