GET http://127.0.0.1:9001/njust/ecommerce-nacos-client/nacos-client/service-instance?serviceId=e-commerce-gateway
Accept: application/json
e-commerce-user: eyJhbGciOiJSUzI1NiJ9.eyJlLWNvbW1lcmNlLXVzZXIiOiJ7XCJpZFwiOjEyLFwidXNlcm5hbWVcIjpcImtvYmVcIn0iLCJqdGkiOiIzYjY0ZjU0Ny1hZGFhLTQyYjYtYmE5NS1hOTYxZTIzOTQ1ZDUiLCJleHAiOjE2NTA3Mjk2MDB9.ActKWoXcZhjwMcupOLy0kPrkCD5mLtEs4rNV8HV1u8HUMRL9VIgAeu_AOZfrY4j4ohraPwqE483vUFJjdj0MQpPZTll5nzpvG0vNRrT1qgUDKmHUSpZurA26l3VsxNx4dZtmvfx0xsH27zubHPoyPiQmx5DrNBUr1kFOLIlNyW9j0_7z5Al0PZydt4WxDwuAekVMPFEsgY3Nfn7YoWvEGYQfPq387ZLZAgUPmna1_U9ete2EnSUmITp1bErFdZHlMtLr8xScpl2elsT7TP331rLmB1g2_qX69uc51Z2APwOg7bYs6nh6JspqHFE4pG5xCtVwsOgM1w8dOTazAH3xxg
token: njust